development:
  adapter: postgresql
  encoding: unicode
  database: angularworkshop_development
  pool: 5
  username: alexis
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: angularworkshop_test
  pool: 5
  username: alexis
  password: 
